### ISSUE TITLE
WIN 7 64位旗舰版 安装报错

### ISSUE THREAD

**Issue by jia58960** [wepyjs/wepy-cli#1]
....
> node-sass@3.13.0 install C:\Users\Eathan\AppData\Roaming\npm\node_modules\wep
-cli\node_modules\node-sass
> node scripts/install.js

install:sass-graph        ▐ ╢█████████████████████████
'node' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
install:sass-graph        ▐ ╢█████████████████████████
postinstall               ▐ ╢█████████████████████████
postinstall               ▐ ╢█████████████████████████
postinstall               ▐ ╢█████████████████████████
postinstall               ▐ ╢█████████████████████████
postinstall               ▐ ╢█████████████████████████
postinstall               ▐ ╢█████████████████████████
postinstall               ▐ ╢█████████████████████████
postinstall               ▐ ╢█████████████████████████
postinstall               ▐ ╢█████████████████████████
npm WARN install:node-sass@3.13.0 node-sass@3.13.0 install: `node scripts/insta
l.js`
npm WARN install:node-sass@3.13.0 Exit status 1
postinstall               ▀ ╢█████████████████████████
postinstall:cli-boxes → l ▄ ╢████████████████████████
postinstall:esutils       ▌ ╢████████████████████████
postinstall:is-binary-pat ▄ ╢████████████████████████
postinstall:is-equal-shal ▌ ╢████████████████████████
postinstall:lowercase-key ▐ ╢█████████████████████████
postinstall:os-tmpdir → l ▐ ╢████████████████████████
postinstall:regenerator-r ▐ ╢█████████████████████████
postinstall:set-immediate ▐ ╢█████████████████████████
postinstall:chalk         ▌ ╢████████████████████████
postinstall:readable-stre ▀ ╢█████████████████████████
postinstall               ▌ ╢████████████████████████
executeActions → rollback ▄ ╢████████████████████████
executeActions → rollback ▌ ╢████████████████████████
runTopLevelLifecycles     ▌ ╢████████████████████████
C:\Users\Eathan\AppData\Roaming\npm
└── (empty)

runTopLevelLifecycles     ▌ ╢████████████████████████
npm ERR! code 1

**Comment by Gcaufy** [comment]
'node' 不是内部或外部命令，也不是可运行的程序

从上面的报错来看是不是你的环境变量有一些问题呢？建议检查一下node的环境变量或者重装一下node试试
